# Generated by Django 5.0.6 on 2024-06-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_video_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='vote',
            field=models.SmallIntegerField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')]),
        ),
    ]
