# Generated by Django 5.0.6 on 2024-06-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_likedislike_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike'), (0, 'Middle')], default=1),
            preserve_default=False,
        ),
    ]
